export const SEARCH_FOCUS = 'SEARCH_FOCUS'
export const SEARCH_BLUR = 'SEARCH_BLUR'

export const SEARCH_TRENDING_LIST = 'SEARCH_TRENDING_LIST'
export const MOUSE_ENTER = 'MOUSE_ENTER'
export const MOUSE_LEAVE = 'MOUSE_LEAVE'
export const CHANGE_PAGE = 'CHANGE_PAGE'
